
[[constraint]]
  branch = "master"
  name = "github.com/go-kit/kit"

[[constraint]]
  branch = "master"
  name = "github.com/gorilla/mux"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

[[constraint]]
  branch = "master"
  name = "github.com/satori/go.uuid"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[prune]
  go-tests = true
  unused-packages = true
